---
- hosts: localhost
  connection: local
  vars:
    packages:
    - git
<<<<<<< HEAD
    - curl
    - cmake
    - python-pip
    - python3-pip
=======
    - cmake
>>>>>>> 29e56ebdf8097ab131922fbdfad0440819a1325d
    - vim
    - vim-gnome
    - tmux
  tasks:
  - name: "Install packages"
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
  - name: Install Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
  - name: Make fonts directory
    file:
      path: ~/.local/share/fonts
      state: directory
  - name: Download powerline-nerd font
    command: curl -fLo "~/.local/share/fonts/Ubuntu Mono derivative Powerline Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete%20Mono.ttf
    args:
      creates: ~/.local/share/fonts/Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
  - name: Copy gitconfig
    copy:
      src: .gitconfig
      dest: ~/.gitconfig
  - name: Copy tmux config
    copy:
      src: "{{ item }}"
      dest: "~/{{ item }}"
    with_items:
    - .tmux.conf
    - .tmux-line.conf
  - name: Copy vimrc
    copy:
      src: .vimrc
      dest: ~/.vimrc
  - name: Install Vim plugins
    command: vim +PluginInstall +qall # Can't provide changed state
