---
- hosts: localhost
  connection: local
  tasks:
  - name: Install Git
    become: yes
    apt:
      name: git
      state: present
  - name: Install Cmake
    become: yes
    apt:
      name: cmake
      state: present
  - name: Install Vim
    become: yes
    apt:
      name: vim
      state: present
  - name: Install gVim
    become: yes
    apt:
      name: vim-gnome # Yeah, GNOME
      state: present
  - name: Install Tmux
    become: yes
    apt:
      name: tmux
      state: present
  - name: Install Vundle
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim
  - name: Make fonts directory
    file:
      path: ~/.local/share/fonts
      state: directory
  - name: Download powerline-nerd font
    command: curl -fLo "~/.local/share/fonts/Ubuntu Mono derivative Powerline Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20derivative%20Powerline%20Nerd%20Font%20Complete.ttf
    args:
      creates: ~/.local/share/fonts/Ubuntu Mono derivative Powerline Nerd Font Complete.ttf
  - name: Copy tmux config
    copy:
      src: "{{ item }}"
      dest: "~/{{ item }}"
    with_items:
    - .tmux.conf
    - .tmux-line.conf
  - name: Copy vimrc
    copy:
      src: .vimrc
      dest: ~/.vimrc
  - name: Install Vim plugins
    command: vim +PluginInstall +qall # Can't provide changed state
